# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/opt/homebrew/bin/ccache
CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CU=/usr/bin/clang
AS=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
GC=/opt/homebrew/Cellar/go/1.27.1/libexec/bin/go
FC=/opt/homebrew/bin/gfortran
SC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend
MM=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CS=/usr/local/share/dotnet/dotnet
MXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
RC=/opt/homebrew/bin/rustc
CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++

LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
GCLD=/opt/homebrew/Cellar/go/1.27.1/libexec/bin/go
FCLD=/opt/homebrew/bin/gfortran
RCLD=/opt/homebrew/bin/rustc
SCLD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc
CS=/usr/local/share/dotnet/dotnet
AR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
GCAR=/opt/homebrew/Cellar/go/1.27.1/libexec/bin/go
RCAR=/opt/homebrew/bin/rustc
SCAR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc
SH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
FCSH=/opt/homebrew/bin/gfortran
RCSH=/opt/homebrew/bin/rustc
SCSH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc

trabalho-U1-edb2_AR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
trabalho-U1-edb2_CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
rsa_LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
rsa_CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
aes_LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
aes_CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

trabalho-U1-edb2_CCFLAGS=-Qunused-arguments -target arm64-apple-macos26.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk -fvisibility=hidden -O3 -DNDEBUG
trabalho-U1-edb2_ARFLAGS=-cr
rsa_CCFLAGS=-Qunused-arguments -target arm64-apple-macos26.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk -fvisibility=hidden -O3 -I/opt/homebrew/opt/gmp/include -DNDEBUG
rsa_LDFLAGS=-target arm64-apple-macos26.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk -lz -L/opt/homebrew/opt/gmp/lib -Lbuild/macosx/arm64/release -Wl,-x -Wl,-dead_strip -lgmp -ltrabalho-U1-edb2
aes_CCFLAGS=-Qunused-arguments -target arm64-apple-macos26.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk -fvisibility=hidden -O3 -DNDEBUG
aes_LDFLAGS=-target arm64-apple-macos26.5 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk -lz -Lbuild/macosx/arm64/release -Wl,-x -Wl,-dead_strip -ltrabalho-U1-edb2

default:  trabalho-U1-edb2 rsa aes

all:  trabalho-U1-edb2 rsa aes

.PHONY: default all  trabalho-U1-edb2 rsa aes

trabalho-U1-edb2: build/macosx/arm64/release/libtrabalho-U1-edb2.a
build/macosx/arm64/release/libtrabalho-U1-edb2.a: build/.objs/trabalho-U1-edb2/macosx/arm64/release/common.c.o
	@echo linking.release libtrabalho-U1-edb2.a
	@mkdir -p build/macosx/arm64/release
	$(VV)$(trabalho-U1-edb2_AR) $(trabalho-U1-edb2_ARFLAGS) build/macosx/arm64/release/libtrabalho-U1-edb2.a build/.objs/trabalho-U1-edb2/macosx/arm64/release/common.c.o

build/.objs/trabalho-U1-edb2/macosx/arm64/release/common.c.o: common.c
	@echo ccache compiling.release common.c
	@mkdir -p build/.objs/trabalho-U1-edb2/macosx/arm64/release
	$(VV)$(trabalho-U1-edb2_CC) -c $(trabalho-U1-edb2_CCFLAGS) -o build/.objs/trabalho-U1-edb2/macosx/arm64/release/common.c.o common.c

rsa: build/macosx/arm64/release/rsa
build/macosx/arm64/release/rsa: build/macosx/arm64/release/libtrabalho-U1-edb2.a build/.objs/rsa/macosx/arm64/release/rsa.c.o
	@echo linking.release rsa
	@mkdir -p build/macosx/arm64/release
	$(VV)$(rsa_LD) -o build/macosx/arm64/release/rsa build/.objs/rsa/macosx/arm64/release/rsa.c.o $(rsa_LDFLAGS)

build/.objs/rsa/macosx/arm64/release/rsa.c.o: rsa.c
	@echo ccache compiling.release rsa.c
	@mkdir -p build/.objs/rsa/macosx/arm64/release
	$(VV)$(rsa_CC) -c $(rsa_CCFLAGS) -o build/.objs/rsa/macosx/arm64/release/rsa.c.o rsa.c

aes: build/macosx/arm64/release/aes
build/macosx/arm64/release/aes: build/macosx/arm64/release/libtrabalho-U1-edb2.a build/.objs/aes/macosx/arm64/release/aes.c.o
	@echo linking.release aes
	@mkdir -p build/macosx/arm64/release
	$(VV)$(aes_LD) -o build/macosx/arm64/release/aes build/.objs/aes/macosx/arm64/release/aes.c.o $(aes_LDFLAGS)

build/.objs/aes/macosx/arm64/release/aes.c.o: aes.c
	@echo ccache compiling.release aes.c
	@mkdir -p build/.objs/aes/macosx/arm64/release
	$(VV)$(aes_CC) -c $(aes_CCFLAGS) -o build/.objs/aes/macosx/arm64/release/aes.c.o aes.c

clean:  clean_trabalho-U1-edb2 clean_rsa clean_aes

clean_trabalho-U1-edb2: 
	@rm -rf build/macosx/arm64/release/libtrabalho-U1-edb2.a
	@rm -rf build/macosx/arm64/release/trabalho-U1-edb2.dSYM
	@rm -rf build/.objs/trabalho-U1-edb2/macosx/arm64/release/common.c.o

clean_rsa:  clean_trabalho-U1-edb2
	@rm -rf build/macosx/arm64/release/rsa
	@rm -rf build/macosx/arm64/release/rsa.dSYM
	@rm -rf build/.objs/rsa/macosx/arm64/release/rsa.c.o

clean_aes:  clean_trabalho-U1-edb2
	@rm -rf build/macosx/arm64/release/aes
	@rm -rf build/macosx/arm64/release/aes.dSYM
	@rm -rf build/.objs/aes/macosx/arm64/release/aes.c.o

